spring.application.name=securecampus
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/freepdb1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=c##securecampus
spring.datasource.password=securecampus123
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false